# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2023.09.21
_src_path: gh:scientific-python/cookie
backend: hatch
email: matt.d.tankersley@gmail.com
full_name: Matt Tankersley
license: MIT
org: mdtanker
project_name: invert4geom
project_short_description: Constrained gravity inversion to recover the geometry of
    a density contrast.
url: https://github.com/mdtanker/invert4geom
vcs: true
