name: CD

# define when this workflow is triggered
on:
  workflow_dispatch:
  push:
    branches:
      - main

# cancel any currently running workflows in this same PR
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # determine appropriate version number, update changelog, and create a release commit
  semantic-release:
    name: Semantic Release
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      # checkout the repo and supply a PAT for the changelog update commit.
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{secrets.PAT}}

      # use semantic-release
      - uses: python-semantic-release/python-semantic-release@master

  # Always build & lint package. Need to re-checkout after semantic-release in case it
  # made a commit
  build-package:
    name: Build & verify package
    runs-on: ubuntu-latest
    needs: semantic-release
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: hynek/build-and-inspect-python-package@v1

  # Download the build package files
  # download-package:
  #   name: Download packages built by build-and-inspect-python-package
  #   needs: build-package
  #   with:
  #     name: Packages
  #     path: dist
  #   uses: actions/download-artifact@v3

  # # Upload to Test PyPI on every commit on main.
  # release-test-pypi:
  #   name: Publish in-dev package to test.pypi.org
  #   needs: [semantic-release, build-package, download-package]
  #   environment:
  #     name: testpypi
  #     url: https://pypi.org/p/invert4geom
  #   permissions:
  #     id-token: write # IMPORTANT: this permission is mandatory for trusted publishing
  #   if: github.ref == 'refs/heads/main'
  #   with:
  #     repository-url: https://test.pypi.org/legacy/
  #   uses: pypa/gh-action-pypi-publish@release/v1

  # # Upload to real PyPI on GitHub Releases.
  # release-pypi:
  #   name: Publish released package to pypi.org
  #   needs: [semantic-release, build-package, download-package]
  #   environment:
  #     name: pypi
  #     url: https://pypi.org/p/invert4geom
  #   permissions:
  #     id-token: write # IMPORTANT: this permission is mandatory for trusted publishing
  #   if: github.ref == 'refs/heads/main'
  #   uses: pypa/gh-action-pypi-publish@release/v1

  # # Upload to GitHub Releases.
  # release-github:
  #   name: Publish package distributions to GitHub Releases
  #   if: steps.semantic-release.outputs.released == 'true'
  #   # if: ${{ always() && contains(join(needs.*.result, ','), 'success') }}
  #   needs: [semantic-release, build-package, download-package]
  #   uses: python-semantic-release/upload-to-gh-release@main
